# Generated by Django 5.1.1 on 2024-09-21 18:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('type', models.CharField(choices=[('Backend Project', 'Backend Project'), ('Frontend Project', 'Frontend Project'), ('IOS Project', 'IOS Project'), ('Android Project', 'Android Project')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=2000)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Resolved', 'Resolved')], default='In Progress', max_length=40)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Incidents', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(15)])),
                ('contacted_prefernce', models.BooleanField(default=False, help_text='Check if the user agrees to be contacted')),
                ('data_sharing', models.BooleanField(default=False, help_text='Check if the user agrees to share their data')),
                ('projects', models.ManyToManyField(to='api.project', verbose_name='Projects this user is contributing to')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.user'),
        ),
    ]
