# Generated by Django 5.1.1 on 2024-09-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='comment',
            new_name='details',
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('Incident', 'Incident'), ('Request', 'Request')], default='Request', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(blank=True, to='api.project', verbose_name='Projects this user is contributing to'),
        ),
    ]
