# Generated by Django 5.1.1 on 2024-09-21 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_comment_incident_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributor',
            field=models.ManyToManyField(blank=True, related_name='contributed_projects', to='api.user', verbose_name='Users registered to this project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to='api.user'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('Incident', 'Incident'), ('Request', 'Request')], default='Request', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=2000)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Resolved', 'Resolved')], default='In Progress', max_length=40)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Incidents', to='api.project')),
            ],
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
    ]
