# Generated by Django 5.1.1 on 2024-09-21 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_contributor_alter_project_creator_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(default='N/A', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='contributor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
