# Generated by Django 5.1.1 on 2024-09-21 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_comment_comment_contributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_ticket',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.ticket'),
            preserve_default=False,
        ),
    ]
