# Generated by Django 5.1.1 on 2024-09-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_comment_comment_text_alter_ticket_ticket_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('High Priority', 'High Priority'), ('Midume Priority', 'Midume Priority'), ('Low Priority', 'Low Priority')], default='Low Priority', max_length=20),
        ),
    ]
