# Generated by Django 5.1.1 on 2024-09-21 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_projects_ticket_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='affected_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Bug ticket', 'Bug'), ('TASK ticket', 'Task'), ('Improvement ticket', 'Improvement Ticket')], default='TASK ticket', max_length=50),
        ),
    ]
