# Generated by Django 5.1.1 on 2024-09-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ticket_affected_user_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='related_ticket', to='api.ticket'),
        ),
    ]
