# Generated by Django 5.1.1 on 2024-09-22 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ticket_assigned_to_alter_ticket_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to='api.user'),
        ),
    ]
