# Generated by Django 5.1.1 on 2024-09-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_project_tickets_remove_ticket_assigned_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contacted_prefernce',
            new_name='contact_preference',
        ),
    ]
