# Generated by Django 5.1.1 on 2024-10-06 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
