# Generated by Django 5.1.1 on 2024-10-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_user_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
