# Generated by Django 5.1.1 on 2024-10-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='mahmoud', max_length=128),
            preserve_default=False,
        ),
    ]
