# Generated by Django 5.1.1 on 2024-10-07 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
