# Generated by Django 5.1.1 on 2024-10-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_user_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contributor_name',
            new_name='contributor_username',
        ),
    ]
