# Generated by Django 5.1.1 on 2024-10-13 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_rename_contributor_name_comment_contributor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.ticket'),
        ),
    ]
