# Generated by Django 5.1.1 on 2024-10-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_comment_parent_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contributor',
            new_name='commenter',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='contributor_username',
            new_name='commenter_name',
        ),
    ]
