# Generated by Django 5.1.1 on 2024-10-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_rename_contributor_comment_commenter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter_name',
            new_name='commenter_username',
        ),
    ]
